debug: false
Plugin:
  language: english
  keep_this_up_to_date: true
  formatting:
    anvil: true
    signs: true
    chat: true
    chat_standard_tags: false
    books: true
    tablist: false
    bossbar: true
    scoreboard: false
    items: true
    packet_events: false
    entity_data: true
  packets:
    disable_glyph_handler: false
WorldEdit:
  fawe_hook: false
  customblock_mechanic: false
  furniture_mechanic: false
Glyphs:
  emoji_list_permission_only: true
  unicode_completions: true
  default_permission: nexo.glyphs.<glyphid>
  default_font: nexo:default
  default_shadow_color: '#00000000'
  hover_text: ''
  shift_font: nexo:shift
  generate_gif_shaders: true
ConfigTools:
  generate_default_configs: true
  disable_automatic_model_data: false
  disable_automatic_glyph_code: false
  initial_custom_model_data: 1000
  skipped_model_data_numbers: []
  error_item:
    material: PODZOL
    injectId: false
  remove_invalid_furniture: false
  invalid_furniture_item:
    material: BARRIER
CustomArmor:
  type: COMPONENT
  auto_assign_settings: true
ItemUpdater:
  update_items: true
  update_items_on_reload: true
  update_tile_entity_contents: true
  update_entity_contents: true
  override_item_lore: false
Misc:
  reset_recipes: true
  add_recipes_to_book: true
  hide_scoreboard_numbers: false
  hide_scoreboard_background: false
  hide_tablist_background: false
  block_other_resourcepacks: false
  default_language_key: en_us
  default_allow_in_vanilla_recipes: false
Recipes:
  require_player_if_permission: true
Pack:
  generation:
    generate_pack: true
    output_path: plugins/Nexo/pack/pack.zip
    prefer_item_models: false
    minimize_json: true
    read_lenient: true
    excluded_file_extensions:
    - .zip
    - .tar.gz
    packsquash:
      enabled: false
      executable_path: plugins/Nexo/pack/packsquash/packsquash
      settings_path: plugins/Nexo/pack/packsquash/packsquash.toml
      cache_size: 5
  obfuscation:
    type: SIMPLE
    cache: true
  import:
    default_assets: true
    external_packs: true
    from_location: []
    from_url: []
    external_pack_order: []
    model_engine:
      import_pack: true
      exclude_shaders: true
  validate:
    models: true
    fonts: true
    atlas: true
    languages: true
  server:
    type: POLYMATH
    selfhost:
      port: 8082
      dispatch_threads: 10
    polymath:
      server: atlas.nexomc.com
      secret: nexomc
    lobfile:
      api_key: API-KEY
    s3:
      public_url: https://fsn1.your-objectstorage.com
      region: eu-central-1
      bucket: nexo-storage
      secret_key: SECRET
      access_key: ACCESS
      url_expiration: 7d
  dispatch:
    send_pre_join: true
    send_on_join: false
    send_on_reload: true
    delay: -1
    mandatory: true
    prompt: <#fa4943>Accept the pack to enjoy a full <b><gradient:#9055FF:#13E2DA>Nexo</b><#fa4943>
      experience
